services:
  postgres_client_api:
    image: postgres
    container_name: postgres_client_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgresql/db
    network_mode: host

  client_api_app:
    container_name: client_api_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres_client_api
    volumes:
      - .:/app/client_api
    network_mode: host
volumes:
  postgres:
    external: true
  app:
    external: true

networks:
  ecom_common:
    external: true