/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace subcriber {
    export interface SubscribersService {
        getAllSubscribers(
            data: GetAllSubscribersParams,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<SubscribersResponse>;
        addSubscriber(
            data: CreateSubscriberDto,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Subscriber>;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface GetAllSubscribersParams {
    }
    export interface SubscribersResponse {
        data?: subcriber.Subscriber[];
    }
    export interface Subscriber {
        id?: number;
        email?: string;
        name?: string;
    }
    export interface CreateSubscriberDto {
        email?: string;
        name?: string;
    }
}

